#!/usr/bin/env python
# -*- coding: utf-8 -*-
import time
import math
import socket
'''
@author: WeiZhang
@date: 2018-01-08
Tailpulse generated by DG4162 function waveform generator via LXI protocal as a input signal on the Gring of CSA
'''
hostname = '192.168.2.4'		#DG4162 function waveform generator ip address
port = 5555						#Rigol instrument port number
#-------------------------------------------------------------------------#
##Write command to device
def write_command(string, sleeptime=0.5):
	s.send(string+"\n")
	time.sleep(sleeptime)
#-------------------------------------------------------------------------#
## generate a tailpulse
def tailPulse(xp=256, np=1024, sigma=0.001):      #generate tail pulse
	amax = 16383
	vals=[0 for i in xrange(np)]
	for i in xrange(np):
		if i<xp:
			vals[i]=amax
		else:
			vals[i]=int(amax*(1-math.exp(-(i-xp)*sigma)))
	string = "DATA:DAC VOLATILE"
	for i in xrange(np):
		string +=(",%d"% vals[i])
	write_command(string, 1.0)
#-------------------------------------------------------------------------#
## main function
def main():
	s.send("*IDN?\n")
	print "Instrument ID: %s"%(s.recv(50))
	tailPulse(xp=128, np=800, sigma=0.01)
	write_command("FREQ 100")
	write_command("VOLT:UNIT VPP")
	write_command("VOLT:LOW 0")
	write_command("VOLT:HIGH %f"%0.1)
	write_command("OUTPut ON")
	print "Ok!"
#-------------------------------------------------------------------------#
## if statement
if __name__ == "__main__":
	s = socket.socket(socket.AF_INET, socket.SOCK_STREAM)       #establish socket
	s.connect((hostname, port))                                 #connet socket
	main()
	s.close
